### ISSUE TITLE
Wrong input type in many fragments.

### ISSUE THREAD

**Issue by ivary43** [openMF/Fineract-CN-mobile#221] opened 2018-04-02 17:55 UTC
**Summary:** 

In many fragments the input type for a phone number is not numeric (i.e 
https://github.com/openMF/Fineract-CN-mobile/blob/c2a3743ca17f56319128377fdc2fea607b8c7e5c/app/src/main/res/layout/fragment_form_customer_contact.xml#L64  
https://github.com/openMF/Fineract-CN-mobile/blob/c2a3743ca17f56319128377fdc2fea607b8c7e5c/app/src/main/res/layout/fragment_form_identification_details.xml#L45
https://github.com/openMF/Fineract-CN-mobile/blob/c2a3743ca17f56319128377fdc2fea607b8c7e5c/app/src/main/res/layout/fragment_form_overview_identification.xml#L46
)

Which should be converted to numeric type.

**Comment by ivary43** [comment] 2018-04-02 17:56
@therajanmaurya  I would like to work on this issue.

**Comment by AkshGautam** [comment] 2018-04-02 18:40
@ivary43 Please check #197 .it's the duplicate of  that

**Closed** 2018-04-03 07:01 UTC
